USERNAME = 10000
LEVEL = 10001
SPECIAL_COUNT = 10002
COMPLETION_TIME = 10003
DEATH_COUNT = 10004
POSITIONS = 10005

SPECIAL_SHEET = 'specialCount'
COMPLETION_SHEET = 'completionTime'
DEATH_SHEET = 'deathCount'
POSITION_SHEET = 'positions'

DEFAULT_PATH = '/Users/kerryoo/VividData/'

LEVEL_COLUMN = 0
SPECIAL_COUNT_COLUMN = 1
COMPLETION_TIME_COLUMN = 1
DEATH_COUNT_COLUMN = 1
TIME_COLUMN = 1
POSITION_X_COLUMN = 2
POSITION_Y_COLUMN = 3
POSITION_Z_COLUMN = 4

LEVEL_INDEX = 0
TIME_INDEX = 1
X_INDEX = 2
Y_INDEX = 3
Z_INDEX = 4